server:
  port: ${randomServerPort.value[2501,3000]}
spring:
  application:
    name: saveorder-service
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/secondkill?characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
      #    最大活跃数
      maxActive: 20
      #  初始化数量
      InitialSize: 1
      #最大连接等待超时时间:
      maxWait: 60000
      #消息队列配置  消费端
  rabbitmq:
    addresses: 192.168.1.100:5672
    username: user
    password: root
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        concurrency: 5
        acknowledge-mode: manual
        max-concurrency: 10
        prefetch: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    instance-id: ${spring.application.name}:${randomServerPort.value[2501,3000]}
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yf.springsaveorder.model
