server:
  port: 8001
eureka:
  instance:
    hostname: eureka-server
    lease-renewal-interval-in-seconds: 2 #心跳间隔
    lease-expiration-duration-in-seconds: 6 #最后一次心跳时间 超过改时间就下线 默认90秒
#  server:
#    enable-self-preservation: false  #关闭自我保护机制
  client:
    register-with-eureka: false #不向自己注册服务
    fetch-registry: false # 不对自己检索服务
    service-url:
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka

