server:
  port: ${randomServerPort.value[1000,2000]}
spring:
  application:
    name: order-service
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/secondkill?characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
      #    最大活跃数
      maxActive: 20
      #  初始化数量
      InitialSize: 1
      #最大连接等待超时时间:
      maxWait: 60000
      #消息队列配置
  rabbitmq:
    addresses: 192.168.1.100:5672
    username: user
    password: root
    virtual-host: /
    connection-timeout: 15000
    publisher-returns: true
    publisher-confirms: true
    template:
      mandatory: true
    http:
      encoding:
        charset: utf-8

  #redis 基本配置
  redis:
    password: root
    host: 192.168.1.100
    port: 6379
    database: 0 #redis 数据库索引
    jedis:
      pool:
        max-active: 8  #连接池最大连接数
        max-wait: -1 #连接池最大组赛时间  负数表示没有限制
        max-idle: 8 #连接池最大空闲数
        min-idle: 0 #连接池最下空闲数
    timeout: 0  #连接超时时间(毫秒)
  session:
    store-type: none  #spring-session 使用

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    instance-id: ${spring.application.name}:${randomServerPort.value[1000,2000]}
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yf.springorder.model
